### ISSUE TITLE
Non Retina images 

### ISSUE THREAD

**Issue by piotr-k** [jrief/angular-retina#13]
Hi. I cannot get images that do not have a @2x version to load with ng-src.  Please advise. Thanks!

**Comment by joelcdoyle** [comment]
@piotr-k Will you please describe the issue? I'm having the same problem. My browser console shows a 404 trying to retrieve the (non-existent) @2x version of the file:

```
GET http://localhost:8100/img/myimage@2x.png 404 (Not Found)
```

My view:
```
<img ng-src="img/myimage.png" />
```

**Comment by pokono** [comment]
Same issue here. If the image returns a 404 shouldn't the library just ignore it and show the standard resolution one?
