### ISSUE TITLE
Provide an attribute to disable retina support element-wise

### ISSUE THREAD

**Issue by vladipus** [jrief/angular-retina#20]
I suggest a new attribute to disable the functionality of the plugin. Sometimes you are absolutely sure, the element does not have a retina version and/or want your own scaling/retina mechanism. In this case something like an `unretinify` attribute would be nice to have. I have made my own, with a simple check like this:

          if (isRetina &&
              typeof $window.sessionStorage === 'object' &&
              element[0].tagName === 'IMG' &&
              attrs.unretinify === undefined &&
              !value.match(data_url_regex)) {
            set2xVariant(value);
          } else {
            setImgSrc(value);
          }

**Comment by vladipus** [comment]
Will this be merged into the `bower install` version?

**Comment by eydreeyawn** [comment]
Thanks for the `noretina` attr. However, I'm getting an error in console, please click the link for screenshot http://screencast.com/t/nDQrvHoNV . It works but I'm getting an error.

**Comment by faceleg** [comment]
@eydreeyawn still getting the error?

**Comment by faceleg** [comment]
@eydreeyawn please repoen if this is still an issue

**Comment by eydreeyawn** [comment]
@faceleg I'm not sure why the error is gone. I think it's all good now. Thanks.

**Comment by faceleg** [comment]
:dancer:
