### ISSUE TITLE
No support for URIs with query paramters after file extension

### ISSUE THREAD

**Issue by JohannUlbrich** [jrief/angular-retina#40]
I have investigated why your directive does not work on my project. I found out that you always check if the image URI ends with one of the supported file extensions. But in my case, the images are delivered from an amazon storage server with a lot of queries at the end of the URI: https://domain.com/hash/fileName.jpg?X-Amz-Algorithm=xxx&X-Amz-Credential=xxx&X-Amz-Date=xxx... So your Regex do not match.

`allowedImageTypesRegex = /(png|jp[e]?g)$/`

`imageUrl.match(allowedImageTypesRegex)
// returns null`

Is it possible to change the regular expression to check not just the end of the URI?

**Comment by faceleg** [comment]
It is definitely possible.

I would suggest that instead of changing the regex. we first parse out the path like this:

```JS
var parser = document.createElement('a');
parser.href = 'https://domain.com/hash/fileName.jpg?X-Amz-Algorithm=xxx&X-Amz-Credential=xxx&X-Amz-Date=xxx';
alert(parser.pathname);
// do the matching against parser.pathname
```

@JohannUlbrich if @jrief agrees with this approach, please feel free to submit a PR.

**Comment by nmalancea** [comment]
@faceleg I submitted a PR for this but the Travis build failed. Possibly due to an older node version or an outdated package. The tests pass fine locally. If you have time take a look at my commit https://github.com/nmalancea/angular-retina/commit/d3f5b2a3efc901dce89ad4568d27446b05f411ec.
