### ISSUE TITLE
When Local Storage is blocked

### ISSUE THREAD

**Issue by CosmoScriv** [jrief/angular-retina#41]
A number of runtime errors are reported from angular-retina.

The use of $window.sessionStorage when local storage is disabled causes the following browser error:

angular.js:12520 Error: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.

Below is the specific line from my example by I see additional references which may also have the issue:

          if (isRetina && angular.isUndefined(attrs.noretina) && typeof **$window.sessionStorage** === 'object' && element[0].tagName === 'IMG' && imageUrl.match(allowedImageTypesRegex) && !imageUrl.match(dataUrlRegex)) {

Any references to $window.sessionStorage should be protected by a try/catch since they may fail on certain browsers.

**Comment by faceleg** [comment]
Yes you're right. There has recently been work to ameliorate this issue, but it hasn't covered all accesses I see.

 - https://github.com/jrief/angular-retina/blob/master/lib/angular-retina.js#L125 should use the getSessionStorageItem function
 - https://github.com/jrief/angular-retina/blob/master/lib/angular-retina.js#L134 should use the setSessionStorageItem function
 - https://github.com/jrief/angular-retina/blob/master/lib/angular-retina.js#L141 should have the sessionStorage check removed? As all attempted accesses would be try/catch, it's OK to just try it anyway?

If you agree, please PR.

**Comment by CosmoScriv** [comment]
Thanks for the quick reply.  I'm a little new to this so can you explain what you mean by:


"If you agree, please PR."



________________________________

**Comment by faceleg** [comment]
Sure, it means I'd be open to accepting a pull request that includes this change. This should give you an overview of a pull request: https://help.github.com/articles/using-pull-requests/

Let me know if you have any questions.

**Comment by CosmoScriv** [comment]
I'm on vacation next week and taking care of my Mom but I'm going to try do it as part of a project that uses angular retina.

Sent from my iPad

On Mar 17, 2016, at 4:37 PM, Michael Robinson <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure, it means I'd be open to accepting a pull request that includes this change. This should give you an overview of a pull request: https://help.github.com/articles/using-pull-requests/

Let me know if you have any questions.

-

**Comment by abachuk** [comment]
I submitted PR 
https://github.com/jrief/angular-retina/pull/42

**Comment by faceleg** [comment]
Thanks @CosmoScriv, @abachuk!
